import { Component, OnDestroy, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpHeaders } from '@angular/common/http';

interface OpcionVirtual { letra: string; texto: string; }
interface PreguntaVirtual { reactivoId: number; numeroPregunta: number; tipoReactivo: string; enunciado: string; opciones: OpcionVirtual[]; }
interface AccesoVirtual { intentoId: string; tokenSesion: string; codigoEstudiante: string; nombreEstudiante: string; codigoSala: string; estadoSala: string; estadoIntento: string; terminaEn?: string; preguntas: PreguntaVirtual[]; }

@Component({
  selector: 'sea-examen-virtual', standalone: true, imports: [CommonModule, FormsModule],
  template: `
    <main class="min-h-screen bg-slate-50 px-4 py-8 text-slate-900"><div class="mx-auto max-w-4xl">
      <header class="mb-6 flex items-center gap-3"><div class="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-600 text-white shadow-lg"><i class="pi pi-check-square text-xl"></i></div><div><p class="text-[10px] font-black uppercase tracking-[.2em] text-indigo-600">UNITEPC · Sistema de Evaluaciones</p><h1 class="text-2xl font-black">Examen virtual</h1></div></header>
      @if (vista() === 'acceso') { <section class="mx-auto max-w-md rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><h2 class="text-lg font-black">Ingresar a la evaluación</h2><p class="mt-1 text-sm text-slate-500">Utiliza el código de sala y el token individual entregado por tu docente.</p><label class="mt-6 block text-xs font-black uppercase tracking-wide">Código de sala</label><input [(ngModel)]="codigoSala" placeholder="SEA-XXXXXX" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold uppercase outline-none focus:border-indigo-500"><label class="mt-4 block text-xs font-black uppercase tracking-wide">Código de estudiante (opcional)</label><input [(ngModel)]="codigoEstudiante" placeholder="Código institucional" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-indigo-500"><label class="mt-4 block text-xs font-black uppercase tracking-wide">Token individual</label><input [(ngModel)]="token" type="password" placeholder="Token entregado" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-indigo-500">@if (error()) { <div class="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{{ error() }}</div> }<button (click)="ingresar()" [disabled]="cargando()" class="mt-6 w-full rounded-xl bg-indigo-600 px-4 py-3 font-black text-white shadow hover:bg-indigo-700 disabled:opacity-50">{{ cargando() ? 'Validando…' : 'Ingresar a la sala' }}</button></section> }
      @if (vista() === 'espera') { <section class="mx-auto max-w-lg rounded-2xl border border-indigo-100 bg-white p-8 text-center shadow-sm"><i class="pi pi-clock text-4xl text-indigo-600"></i><h2 class="mt-4 text-xl font-black">Estás en la sala de espera</h2><p class="mt-2 text-sm text-slate-500">{{ acceso()?.nombreEstudiante }}. El docente debe iniciar el examen. Esta página se actualizará automáticamente.</p><div class="mt-6 rounded-xl bg-indigo-50 p-4 text-left text-sm"><b>Sala:</b> {{ acceso()?.codigoSala }}<br><b>Estado:</b> Esperando inicio</div></section> }
      @if (vista() === 'examen' && acceso(); as examen) { <section class="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><p class="text-xs font-black uppercase tracking-wide text-indigo-600">{{ examen.codigoSala }}</p><h2 class="text-lg font-black">{{ examen.nombreEstudiante }}</h2></div><div class="rounded-xl bg-rose-50 px-4 py-2 text-center text-rose-700"><span class="block text-[10px] font-black uppercase">Tiempo restante</span><b class="font-mono text-xl">{{ tiempoRestante() }}</b></div></section><section class="space-y-4">@for (pregunta of examen.preguntas; track pregunta.numeroPregunta) { <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex gap-3"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-indigo-50 font-black text-indigo-700">{{ pregunta.numeroPregunta }}</span><p class="font-semibold leading-6">{{ pregunta.enunciado }}</p></div><div class="mt-4 grid gap-2 sm:grid-cols-2">@for (opcion of pregunta.opciones; track opcion.letra) { <label class="flex cursor-pointer gap-3 rounded-xl border p-3 transition hover:border-indigo-300" [class.border-indigo-500]="respuestas[pregunta.numeroPregunta] === opcion.letra" [class.bg-indigo-50]="respuestas[pregunta.numeroPregunta] === opcion.letra"><input type="radio" [name]="'pregunta-' + pregunta.numeroPregunta" [value]="opcion.letra" [checked]="respuestas[pregunta.numeroPregunta] === opcion.letra" (change)="responder(pregunta, opcion.letra)" class="mt-1 accent-indigo-600"><span><b>{{ opcion.letra }})</b> {{ opcion.texto }}</span></label> }</div></article> }</section><div class="sticky bottom-4 mt-6 flex justify-end"><button (click)="enviar()" class="rounded-xl bg-emerald-600 px-6 py-3 font-black text-white shadow-lg hover:bg-emerald-700">Finalizar examen</button></div> }
      @if (vista() === 'finalizado') { <section class="mx-auto max-w-lg rounded-2xl border border-emerald-100 bg-white p-8 text-center shadow-sm"><i class="pi pi-check-circle text-5xl text-emerald-600"></i><h2 class="mt-4 text-xl font-black">Examen enviado</h2><p class="mt-2 text-sm text-slate-500">Tu intento fue registrado correctamente.</p></section> }
    </div></main>`
})
export class ExamenVirtualComponent implements OnDestroy {
  private readonly http = inject(HttpClient); vista = signal<'acceso' | 'espera' | 'examen' | 'finalizado'>('acceso'); acceso = signal<AccesoVirtual | null>(null); cargando = signal(false); error = signal('');
  codigoSala = ''; codigoEstudiante = ''; token = ''; respuestas: Record<number, string> = {}; private polling?: ReturnType<typeof setInterval>; private reloj?: ReturnType<typeof setInterval>; private segundos = 0;
  ingresar(): void { this.error.set(''); this.cargando.set(true); this.http.post<AccesoVirtual>('/api/acceso-virtual/validar', { codigoSala: this.codigoSala.trim(), codigoEstudiante: this.codigoEstudiante.trim(), token: this.token.trim() }).subscribe({ next: data => { this.acceso.set(data); this.cargando.set(false); this.actualizarVista(data); }, error: err => { this.cargando.set(false); this.error.set(err?.error?.error || 'No se pudo validar el acceso.'); } }); }
  responder(pregunta: PreguntaVirtual, respuesta: string): void { this.respuestas[pregunta.numeroPregunta] = respuesta; const headers = new HttpHeaders({ 'X-Examen-Token': this.acceso()?.tokenSesion || this.token }); this.http.put('/api/examen-virtual/respuestas', { numeroPregunta: pregunta.numeroPregunta, reactivoId: pregunta.reactivoId, respuesta }, { headers }).subscribe({ error: () => this.error.set('No se pudo guardar la última respuesta.') }); }
  enviar(): void { if (!confirm('¿Deseas finalizar y enviar el examen?')) return; const headers = new HttpHeaders({ 'X-Examen-Token': this.acceso()?.tokenSesion || this.token }); this.http.post('/api/examen-virtual/enviar', {}, { headers }).subscribe({ next: () => { this.detener(); this.vista.set('finalizado'); }, error: err => this.error.set(err?.error?.error || 'No se pudo enviar el examen.') }); }
  tiempoRestante(): string { return `${Math.floor(this.segundos / 60).toString().padStart(2, '0')}:${(this.segundos % 60).toString().padStart(2, '0')}`; }
  private actualizarVista(data: AccesoVirtual): void { if (data.estadoSala === 'EN_CURSO' && data.preguntas?.length) { this.detenerPolling(); this.vista.set('examen'); this.iniciarReloj(data.terminaEn); return; } this.vista.set('espera'); if (!this.polling) this.polling = setInterval(() => this.recargar(), 3000); }
  private recargar(): void { const headers = new HttpHeaders({ 'X-Examen-Token': this.acceso()?.tokenSesion || this.token }); this.http.get<AccesoVirtual>('/api/examen-virtual/actual', { headers }).subscribe({ next: data => { this.acceso.set(data); this.actualizarVista(data); }, error: err => this.error.set(err?.error?.error || 'Se perdió la conexión con la sala.') }); }
  private iniciarReloj(terminaEn?: string): void { this.detenerReloj(); if (!terminaEn) return; const fin = new Date(terminaEn).getTime(); const tick = () => { this.segundos = Math.max(0, Math.floor((fin - Date.now()) / 1000)); if (!this.segundos) this.enviar(); }; tick(); this.reloj = setInterval(tick, 1000); }
  private detenerPolling(): void { if (this.polling) { clearInterval(this.polling); this.polling = undefined; } }
  private detenerReloj(): void { if (this.reloj) { clearInterval(this.reloj); this.reloj = undefined; } } private detener(): void { this.detenerPolling(); this.detenerReloj(); } ngOnDestroy(): void { this.detener(); }
}
