import { Component, OnDestroy, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { Observable, Subscription, interval } from 'rxjs';

interface Participante { codigoEstudiante: string; nombreEstudiante: string; estado: string; }
interface Sala { id: string; rolExamenId: string; codigoSala: string; estado: string; duracionMinutos: number; participantes: Participante[]; }
interface Acceso { codigoEstudiante: string; nombreEstudiante: string; token: string; }
interface Creada { sala: Sala; accesos: Acceso[]; }

@Component({
  selector: 'sea-sala-virtual', standalone: true, imports: [CommonModule, FormsModule],
  template: `
    <div class="space-y-6 animate-fade-in"><header><p class="text-[10px] font-black uppercase tracking-[.2em] text-primary">Operación virtual</p><h1 class="text-2xl font-black text-foreground">Salas de examen virtual</h1><p class="mt-1 text-sm text-muted-foreground">Usa las variantes y asignaciones ya generadas para organizar el ingreso de estudiantes.</p></header>
      @if (!sala()) { <section class="max-w-xl rounded-2xl border border-border bg-card p-6 shadow-xs"><h2 class="font-black text-foreground">Crear sala desde un examen generado</h2><p class="mt-1 text-xs text-muted-foreground">El rol debe tener modalidad Virtual, banco validado y variantes generadas.</p><label class="mt-5 block text-[10px] font-black uppercase tracking-wide text-muted-foreground">ID del rol de examen</label><input [(ngModel)]="rolExamenId" placeholder="ROL-GRUPO-1P-FECHA" class="mt-2 w-full rounded-xl border border-border bg-muted/50 px-3 py-3 text-sm font-mono outline-none focus:border-primary"><div class="mt-4 grid grid-cols-2 gap-3"><div><label class="block text-[10px] font-black uppercase tracking-wide text-muted-foreground">Duración (minutos)</label><input [(ngModel)]="duracion" type="number" min="1" max="480" class="mt-2 w-full rounded-xl border border-border bg-muted/50 px-3 py-3 text-sm outline-none focus:border-primary"></div><div><label class="block text-[10px] font-black uppercase tracking-wide text-muted-foreground">Gracia de ingreso</label><input [(ngModel)]="gracia" type="number" min="0" max="60" class="mt-2 w-full rounded-xl border border-border bg-muted/50 px-3 py-3 text-sm outline-none focus:border-primary"></div></div>@if (error()) { <div class="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{{ error() }}</div> }<button (click)="crear()" [disabled]="cargando()" class="mt-5 rounded-xl bg-primary px-5 py-3 text-xs font-black text-white shadow hover:opacity-90 disabled:opacity-50">{{ cargando() ? 'Creando…' : 'Crear sala y generar accesos' }}</button></section> }
      @if (sala(); as actual) { <section class="rounded-2xl border border-border bg-card p-6 shadow-xs"><div class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-[10px] font-black uppercase tracking-widest text-muted-foreground">Sala {{ actual.codigoSala }}</p><h2 class="text-xl font-black text-foreground">{{ actual.rolExamenId }}</h2><span class="mt-2 inline-flex rounded-full bg-indigo-50 px-3 py-1 text-[10px] font-black uppercase text-indigo-700">{{ actual.estado }}</span></div><div class="flex gap-2">@if (actual.estado === 'PREPARADA') { <button (click)="abrir()" class="rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-2 text-xs font-black text-indigo-700">Abrir sala</button> } @if (actual.estado === 'ABIERTA') { <button (click)="iniciar()" class="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black text-white">Iniciar examen</button> } @if (actual.estado === 'EN_CURSO') { <button (click)="cerrar()" class="rounded-xl bg-rose-600 px-4 py-2 text-xs font-black text-white">Cerrar sala</button> }</div></div><div class="mt-6 grid gap-3 sm:grid-cols-3"><div class="rounded-xl bg-muted/50 p-4"><span class="text-[10px] font-black uppercase text-muted-foreground">Estudiantes</span><b class="mt-1 block text-2xl font-black">{{ actual.participantes.length }}</b></div><div class="rounded-xl bg-muted/50 p-4"><span class="text-[10px] font-black uppercase text-muted-foreground">En espera</span><b class="mt-1 block text-2xl font-black">{{ contar('EN_ESPERA') }}</b></div><div class="rounded-xl bg-muted/50 p-4"><span class="text-[10px] font-black uppercase text-muted-foreground">En curso</span><b class="mt-1 block text-2xl font-black">{{ contar('EN_CURSO') }}</b></div></div></section>
        @if (accesos().length) { <section class="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div class="flex items-center justify-between"><div><h2 class="font-black text-amber-900">Tokens individuales</h2><p class="text-xs text-amber-800">Guárdalos y entrégalos individualmente. No se vuelven a mostrar después de salir de esta pantalla.</p></div><button (click)="accesos.set([])" class="text-xs font-bold text-amber-800">Ocultar tokens</button></div><div class="mt-4 overflow-x-auto"><table class="w-full text-left text-xs"><thead><tr class="border-b border-amber-200 text-[10px] uppercase text-amber-800"><th class="p-2">Estudiante</th><th class="p-2">Token</th></tr></thead><tbody>@for (acceso of accesos(); track acceso.codigoEstudiante) { <tr class="border-b border-amber-100"><td class="p-2 font-bold">{{ acceso.codigoEstudiante }} · {{ acceso.nombreEstudiante }}</td><td class="p-2 font-mono">{{ acceso.token }}</td></tr> }</tbody></table></div></section> }
        <section class="rounded-2xl border border-border bg-card p-6 shadow-xs"><h2 class="font-black text-foreground">Participantes</h2><div class="mt-4 overflow-x-auto"><table class="w-full text-left text-xs"><thead><tr class="border-b border-border text-[10px] uppercase text-muted-foreground"><th class="p-2">Código</th><th class="p-2">Estudiante</th><th class="p-2">Estado</th></tr></thead><tbody>@for (participante of actual.participantes; track participante.codigoEstudiante) { <tr class="border-b border-border"><td class="p-2 font-mono font-bold">{{ participante.codigoEstudiante }}</td><td class="p-2">{{ participante.nombreEstudiante }}</td><td class="p-2"><span class="rounded-full bg-muted px-2 py-1 text-[10px] font-black">{{ participante.estado }}</span></td></tr> }</tbody></table></div></section>
      }
    </div>`
})
export class SalaVirtualComponent implements OnDestroy {
  private readonly http = inject(HttpClient); sala = signal<Sala | null>(null); accesos = signal<Acceso[]>([]); cargando = signal(false); error = signal(''); rolExamenId = ''; duracion = 90; gracia = 10;
  private monitoreo?: Subscription;
  crear(): void { this.ejecutar(this.http.post<Creada>('/api/examenes-virtuales/salas', { rolExamenId: this.rolExamenId.trim(), duracionMinutos: this.duracion, graciaIngresoMinutos: this.gracia }), data => { this.sala.set(data.sala); this.accesos.set(data.accesos || []); this.iniciarMonitoreo(); }); }
  abrir(): void { this.cambiarEstado('abrir'); } iniciar(): void { this.cambiarEstado('iniciar'); } cerrar(): void { this.cambiarEstado('cerrar'); }
  contar(estado: string): number { return this.sala()?.participantes.filter(p => p.estado === estado).length || 0; }
  private cambiarEstado(accion: string): void { const id = this.sala()?.id; if (!id) return; this.ejecutar(this.http.post<Sala>(`/api/examenes-virtuales/salas/${id}/${accion}`, {}), data => { this.sala.set(data); if (accion === 'cerrar') this.detenerMonitoreo(); }); }
  private iniciarMonitoreo(): void { this.detenerMonitoreo(); this.monitoreo = interval(3000).subscribe(() => this.actualizarSala()); }
  private actualizarSala(): void { const id = this.sala()?.id; if (!id) return; this.http.get<Sala>(`/api/examenes-virtuales/salas/${id}`).subscribe({ next: data => { this.sala.set(data); if (['CERRADA', 'CALIFICADA', 'ANULADA'].includes(data.estado)) this.detenerMonitoreo(); } }); }
  private detenerMonitoreo(): void { this.monitoreo?.unsubscribe(); this.monitoreo = undefined; }
  private ejecutar<T>(request: Observable<T>, next: (data: T) => void): void { this.cargando.set(true); this.error.set(''); request.subscribe({ next: data => { this.cargando.set(false); next(data); }, error: err => { this.cargando.set(false); this.error.set(err?.error?.error || 'No se pudo completar la operación.'); } }); }
  ngOnDestroy(): void { this.detenerMonitoreo(); }
}
